### ISSUE TITLE
feat: BottomSheet 의 전반적인 UI와 뷰의 기능을 구현합니다.

### ISSUE THREAD

**Issue by LeeSungNo-ian** [LeeSungNo-ian/AirPollution-Weather-APP#13]
## 🎯 이슈 개요
| 이슈 내용 | BottomSheet 의 전반적인 UI와 뷰의 기능을 구현합니다. |
| --- | --- |
| 마감 일자 | 2022. 10. 11 |

## 🏹 Todo
 - [x] 도시의 이름값을 받아오는 TextField를 구현합니다.
 - [x] TextField Delegate 를 이용해 UIView의 크기를 조절합니다.
 - [x] 현재 도시의 날씨가 보이는 화면을 구현합니다.
