### ISSUE TITLE
feat: 미세먼지 수치를 직관적인 워딩으로 사용자에게 보여줍니다.

### ISSUE THREAD

**Issue by LeeSungNo-ian** [LeeSungNo-ian/AirPollution-Weather-APP#19]
## 🎯 이슈 개요
| 이슈 내용 | 미세먼지 수치를 직관적인 워딩으로 사용자에게 보여줍니다.
| --- | --- |
| 마감 일자 | 2022. 10. 13 |

## 🏹 Todo
 - [x] 미세먼지 수치에 따른 워딩을 설정합니다.
 - [x] 미세먼지 수치에 따라 안내문구가 변경됩니다.
 - [x] 우측 하단의 컨텐츠를 변경합니다.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/78950704/195448696-0dbcd13e-6c29-44f4-b8c9-b8631c9e6064.png">
